-- liquibase formatted sql

-- changeset Administrator:1616795601000-1
CREATE SEQUENCE SEQEXEMPLAR START WITH 14 MAXVALUE 9999999999999999999999999999 NOCACHE;

-- changeset Administrator:1616795601000-2
CREATE TABLE T_EXEMPLAR (EXEMPLAR_ID NUMBER(*, 0) NOT NULL, FILM_ID NUMBER(*, 0) NOT NULL, MEDIUM_ID NUMBER(*, 0) NOT NULL, PRICE_PER_DAY NUMBER(*, 0), CONSTRAINT PK_T_EXEMPLAR PRIMARY KEY (EXEMPLAR_ID)) TABLESPACE USERS;

-- changeset Administrator:1616795601000-3
CREATE TABLE T_FILM (FILM_ID NUMBER(*, 0) NOT NULL, TITLE VARCHAR2(50 CHAR) NOT NULL, DIRECTOR VARCHAR2(30 CHAR) NOT NULL, PRODUCTION_COMPANY VARCHAR2(50 CHAR), GENRE_ID NUMBER(*, 0) NOT NULL, MIN_AGE NUMBER(*, 0), FILM_ID_EPISODES NUMBER(*, 0), CONSTRAINT PK_T_FILM PRIMARY KEY (FILM_ID)) TABLESPACE USERS;
COMMENT ON COLUMN T_FILM.PRODUCTION_COMPANY IS 'Company name must contain also information about company type - LTD, Inc. and so on.';

-- changeset Administrator:1616795601000-4
CREATE TABLE T_BORROWING (EXEMPLAR_ID NUMBER(*, 0) NOT NULL, CUSTOMER_ID NUMBER(*, 0) NOT NULL, START_DATE date DEFAULT SYSDATE, END_DATE date, TOTAL_PRICE PRICE_TYPE, VAT NUMBER(4, 2) DEFAULT 19, CONSTRAINT PK_T_BORROWING PRIMARY KEY (EXEMPLAR_ID)) TABLESPACE USERS;
COMMENT ON TABLE T_BORROWING IS 'Borrowed items';

-- changeset Administrator:1616795601000-5
CREATE TABLE T_CUSTOMER (CUSTOMER_ID NUMBER(*, 0) NOT NULL, NAME VARCHAR2(20 CHAR), ADDRESS CUST_ADDRESS_TYPE, CONSTRAINT PK_T_CUSTOMER PRIMARY KEY (CUSTOMER_ID)) TABLESPACE USERS;
COMMENT ON COLUMN T_CUSTOMER.NAME IS 'Name column can contain First and Middle name. Surname must be in different column.';

-- changeset Administrator:1616795601000-6
CREATE OR REPLACE FORCE VIEW "V_CUSTOMER_HAS_FILM" ("NAME", "CITY", "TITLE", "DIRECTOR") AS SELECT DISTINCT c.name, c.address.city AS city, f.title, f.director
FROM T_CUSTOMER c, T_BORROWING b, T_EXEMPLAR e, T_FILM f
WHERE c.customer_id=b.customer_id 
and b.exemplar_id=e.exemplar_id 
and e.film_id=f.film_id;

-- changeset Administrator:1616795601000-7
CREATE TABLE T_CUSTOMER_RATING (TITLE VARCHAR2(50 CHAR) NOT NULL, DIRECTOR VARCHAR2(30 CHAR) NOT NULL, RATING NUMBER(*, 0) DEFAULT 3, CONSTRAINT PK_T_CUSTOMER_RATING PRIMARY KEY (TITLE, DIRECTOR)) TABLESPACE USERS;
COMMENT ON TABLE T_CUSTOMER_RATING IS 'Movie ratings (by customers)';

-- changeset Administrator:1616795601000-8
CREATE TABLE T_GENRE (GENRE_ID NUMBER(*, 0) NOT NULL, NAME VARCHAR2(20 CHAR), CONSTRAINT PK_T_GENRE PRIMARY KEY (GENRE_ID)) TABLESPACE USERS;

-- changeset Administrator:1616795601000-9
CREATE TABLE T_MEDIUM (MEDIUM_ID NUMBER(*, 0) NOT NULL, MEDIUM_TYPE VARCHAR2(20 BYTE), CONSTRAINT PK_T_MEDIUM PRIMARY KEY (MEDIUM_ID)) TABLESPACE USERS;

-- changeset Administrator:1616795601000-10
CREATE TABLE T_ORDER_RECORD (CUSTOMER_ID NUMBER(*, 0) NOT NULL, FILM_ID NUMBER(*, 0) NOT NULL, ORDER_DATE date, CONSTRAINT PK_T_ORDER_RECORD PRIMARY KEY (CUSTOMER_ID, FILM_ID)) TABLESPACE USERS;
COMMENT ON TABLE T_ORDER_RECORD IS 'All records are stored in list of records. It will be possible to book a movie.';

-- changeset Administrator:1616795601000-11
CREATE UNIQUE INDEX AK_EXEMPLAR_PPD ON T_EXEMPLAR(EXEMPLAR_ID, PRICE_PER_DAY);

-- changeset Administrator:1616795601000-12
ALTER TABLE T_EXEMPLAR ADD CONSTRAINT AK_EXEMPLAR_PPD UNIQUE (EXEMPLAR_ID, PRICE_PER_DAY) USING INDEX AK_EXEMPLAR_PPD;

-- changeset Administrator:1616795601000-13
CREATE UNIQUE INDEX AK_TITLE_DIRECTOR ON T_FILM(TITLE, DIRECTOR);

-- changeset Administrator:1616795601000-14
ALTER TABLE T_FILM ADD CONSTRAINT AK_TITLE_DIRECTOR UNIQUE (TITLE, DIRECTOR) USING INDEX AK_TITLE_DIRECTOR;

-- changeset Administrator:1616795601000-15
CREATE INDEX I_NAME ON T_CUSTOMER(NAME);

-- changeset Administrator:1616795601000-16
ALTER TABLE T_EXEMPLAR ADD CONSTRAINT HAS FOREIGN KEY (FILM_ID) REFERENCES T_FILM (FILM_ID);

-- changeset Administrator:1616795601000-17
ALTER TABLE T_FILM ADD CONSTRAINT HAS_MORE_EPISODES FOREIGN KEY (FILM_ID_EPISODES) REFERENCES T_FILM (FILM_ID);

-- changeset Administrator:1616795601000-18
ALTER TABLE T_EXEMPLAR ADD CONSTRAINT IS_AVAILABLE_ON FOREIGN KEY (MEDIUM_ID) REFERENCES T_MEDIUM (MEDIUM_ID);

-- changeset Administrator:1616795601000-19
ALTER TABLE T_FILM ADD CONSTRAINT IS_OF FOREIGN KEY (GENRE_ID) REFERENCES T_GENRE (GENRE_ID);

-- changeset Administrator:1616795601000-20
ALTER TABLE T_CUSTOMER_RATING ADD CONSTRAINT IS_RATED FOREIGN KEY (TITLE, DIRECTOR) REFERENCES T_FILM (TITLE, DIRECTOR);

-- changeset Administrator:1616795601000-21
ALTER TABLE T_BORROWING ADD CONSTRAINT IS_RELATED_TO FOREIGN KEY (EXEMPLAR_ID) REFERENCES T_EXEMPLAR (EXEMPLAR_ID);

-- changeset Administrator:1616795601000-22
ALTER TABLE T_ORDER_RECORD ADD CONSTRAINT IS_REQUIRED_BY FOREIGN KEY (FILM_ID) REFERENCES T_FILM (FILM_ID);

-- changeset Administrator:1616795601000-23
ALTER TABLE T_BORROWING ADD CONSTRAINT MAKES FOREIGN KEY (CUSTOMER_ID) REFERENCES T_CUSTOMER (CUSTOMER_ID);

-- changeset Administrator:1616795601000-24
ALTER TABLE T_ORDER_RECORD ADD CONSTRAINT PLACES FOREIGN KEY (CUSTOMER_ID) REFERENCES T_CUSTOMER (CUSTOMER_ID);

